#!/usr/bin/env ruby
#/ Usage: abandon [options] <todo_id>
#/ Mark a todo item as abandoned via the Todo web API.
#/    -a, --abandoned_on  abandoned_on      Date item was abandoned (default is today)
#/    -h, --help                            Show help

require 'optparse'
require 'optparse/date'
require 'securerandom'
require 'net/http'
require 'uri'
require 'json'

todo_id = nil
abandoned_on = Date.today

ARGV.options do |opts|
  opts.on('-a', '--abandoned_on abandoned_on', Date) { |date| abandoned_on = date }
  opts.on_tail('-h', '--help') { exec "grep ^#/<'#{__FILE__}'|cut -c4-" }

  opts.parse!
end

todo_id = ARGV[0]

unless todo_id
  $stderr.puts "Error: you must specify a todo_id to abandon"
  exit 1
end

payload = {
  abandoned_on: abandoned_on,
}.compact

puts "Abandoning todo [#{todo_id}]: #{payload}"
uri = URI.parse("http://localhost:3000/todo/#{todo_id}/abandon")
http = Net::HTTP.new(uri.host, uri.port)
request = Net::HTTP::Post.new(uri.path, 'Content-Type': 'text/json')
request.body = payload.to_json

response = http.request(request)

if response.code != '200'
  $stderr.puts 'Failed to abandon todo'
  $stderr.puts response.body
  exit 1
end
