#!/usr/bin/env ruby
#/ Usage: list [options] <outstanding|completed|scheduled>
#/ Show the list of todo items via the Todo web API.
#/    outstanding                     Show outstanding todos
#/    scheduled                       Show scheduled todos
#/    completed                       Show completed todos
#/    -h, --help                      Show help

require 'optparse'
require 'optparse/date'
require 'securerandom'
require 'net/http'
require 'uri'
require 'json'

LISTS = [
  'outstanding',
  'scheduled',
  'completed',
]

ARGV.options do |opts|
  opts.on_tail('-h', '--help') { exec "grep ^#/<'#{__FILE__}'|cut -c4-" }

  opts.parse!
end

list_name = ARGV[0] || ''

unless LISTS.include?(list_name.downcase)
  $stderr.puts "Error: you must specify which todos to list <outstanding|completed|scheduled>"
  exit 1
end

puts "#{list_name.capitalize} todos"
uri = URI.parse("http://localhost:3000/todos/#{list_name}")
http = Net::HTTP.new(uri.host, uri.port)
request = Net::HTTP::Get.new(uri.path, 'Content-Type': 'application/json')

response = http.request(request)

if response.code != '200'
  $stderr.puts 'Failed to get #{list_name} todos'
  $stderr.puts response.body
  exit 1
end

puts JSON.parse(response.body)
