#!/usr/bin/env bash

if ! type -t "bundle" > /dev/null; then
  echo
  echo "--- Installing Bundler"
  echo

  gem install 'bundler:$(tail -1 Gemfile.lock | tr -d '[:space:]')'
fi

if ! type -t "foreman" > /dev/null; then
  echo
  echo "--- Installing Foreman"
  echo

  gem install foreman
fi

echo
echo "--- Installing gems"
echo

bundle install

echo
echo "--- Creating and migrating databases"
echo

bundle exec rake db:create db:migrate
RACK_ENV=test bundle exec rake db:create db:migrate


echo
echo "--- Setting up event processors"
echo

bundle exec rake setup_processors
RACK_ENV=test bundle exec rake setup_processors
